__title__ = 'shecan'
__description__ = 'The Shecan CLI is used to configure your DNS configuration based on Shecan website from the command line.'
__url__ = 'https://github.com/GreatBahram/shecan-cli'
__version__ = '0.2.2'
__author__ = 'Bahram Aghaei'
__author_email__ = 'aghaee.bahram@gmail.com'
__license__ = 'Academic Free License, version 3'
