name: "Run the test and formatter"

on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                cache: pip
                cache-dependency-path: pyproject.toml
            - name: Install dependencies
              run: |
                pip install '.[dev]'
            - name: Run tests
              run: |
                pytest
            - name: Run formatter  & linter
              run: |
                ruff check .
                ruff format . --check